In [ ]:
from pathlib import Path

import pandas as pd

from feature_engineering import build_features

SEASON = 2026

players_per_round_file = Path("data") / f"jogadores_por_rodada_{SEASON}.parquet"
players_per_round_df = pd.read_parquet(players_per_round_file)

matches_file = Path("data") / f"partidas_{SEASON}.parquet"
matches_df = pd.read_parquet(matches_file)

FileNotFoundError: [Errno 2] No such file or directory: 'data\\jogadores_por_rodada_2026.parquet'

In [14]:
players_per_round_df.describe()

,rodada,atleta_id,posicao_id,clube_id,status_id,pontos,preco,media,jogos,temporada,...,scout_CA,scout_SG,scout_GS,scout_G,scout_CV,scout_PP,scout_PC,scout_FT,scout_DP,scout_GC
count,28589.0,28589.0,28589.0,28589.0,28589.0,28589.000000,28589.000000,28589.000000,28589.0,28589.0,...,27970.000000,27970.000000,27970.000000,27970.000000,27970.000000,27970.000000,27970.00000,27970.000000,27970.000000,27970.000000
mean,20.143867,105250.278534,3.500122,372.820735,6.075798,1.459945,5.359234,2.429026,7.548952,2025.0,...,1.131248,0.875795,0.557276,0.562710,0.051233,0.014122,0.06010,0.153236,0.010654,0.010905
std,10.90789,23116.741698,1.353824,414.770927,0.92311,3.071350,3.219350,2.302912,7.94669,0.0,...,1.707667,2.124588,3.439006,1.449478,0.230002,0.117997,0.26914,0.459961,0.130295,0.105224
min,1.0,37281.0,1.0,262.0,2.0,-4.700000,0.630000,-3.600000,0.0,2025.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,11.0,90285.0,2.0,266.0,6.0,0.000000,3.000000,0.000000,0.0,2025.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,20.0,104519.0,4.0,280.0,6.0,0.000000,5.000000,2.230000,5.0,2025.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
75%,30.0,122573.0,5.0,287.0,7.0,1.500000,7.190000,3.930000,12.0,2025.0,...,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
max,38.0,147007.0,6.0,2305.0,7.0,33.100000,25.000000,18.900000,38.0,2025.0,...,13.000000,18.000000,50.000000,21.000000,2.000000,1.000000,4.00000,5.000000,3.000000,2.000000

In [15]:
features_df = build_features(players_per_round_df, matches_df)

In [16]:
features_df.describe()

,rodada,atleta_id,posicao_id,clube_id,status_id,pontos,preco,media,jogos,temporada,...,pts_ultima_rodada,acc_scout_G,acc_scout_A,acc_scout_SG,acc_scout_GS,regularidade_5r,preco_lag1,mando,posicao_enc,clube_enc
count,28589.0,28589.0,28589.0,28589.0,28589.0,28589.000000,28589.000000,28589.000000,28589.0,28589.0,...,27609.000000,27609.000000,27609.000000,27609.000000,27609.000000,27609.000000,27609.000000,28589.000000,28589.000000,28589.000000
mean,20.143867,105250.278534,3.500122,372.820735,6.075798,1.459945,5.359234,2.429026,7.548952,2025.0,...,1.465401,0.482209,0.323536,0.754937,0.474729,0.327536,5.370916,-0.002099,3.500122,9.556648
std,10.90789,23116.741698,1.353824,414.770927,0.92311,3.071350,3.219350,2.302912,7.94669,0.0,...,3.075357,1.298198,0.840175,1.914724,3.059823,0.343395,3.223128,0.972906,1.353824,5.771182
min,1.0,37281.0,1.0,262.0,2.0,-4.700000,0.630000,-3.600000,0.0,2025.0,...,-4.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.630000,-1.000000,1.000000,0.000000
25%,11.0,90285.0,2.0,266.0,6.0,0.000000,3.000000,0.000000,0.0,2025.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,-1.000000,2.000000,5.000000
50%,20.0,104519.0,4.0,280.0,6.0,0.000000,5.000000,2.230000,5.0,2025.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,5.000000,0.000000,4.000000,10.000000
75%,30.0,122573.0,5.0,287.0,7.0,1.500000,7.190000,3.930000,12.0,2025.0,...,1.500000,0.000000,0.000000,0.000000,0.000000,0.600000,7.190000,1.000000,5.000000,15.000000
max,38.0,147007.0,6.0,2305.0,7.0,33.100000,25.000000,18.900000,38.0,2025.0,...,33.100000,19.800000,13.600000,16.800000,49.400000,1.000000,25.000000,1.000000,6.000000,19.000000