In [30]:
import pandas as pd

from cartola_collector import read_datasets

df_players_per_round, df_matches = read_datasets()
df_players_per_round.temporada.describe()

count    96401.000000
mean      2024.228774
std          0.996022
min       2023.000000
25%       2023.000000
50%       2024.000000
75%       2025.000000
max       2026.000000
Name: temporada, dtype: float64

In [31]:
df_ppr_2026 = df_players_per_round[df_players_per_round.temporada == 2026]

In [34]:
rodada_15 = df_ppr_2026[df_ppr_2026.rodada == 15]
rodada_15

,rodada,atleta_id,apelido,posicao_id,clube_id,clube_abreviacao,status_id,pontos,preco,media,...,scout_A,scout_FT,scout_PC,scout_V,scout_PS,scout_PP,scout_CV,jogou,scout_GC,clube_nome
95651,15,37457,Léo Condé,6,364,REM,7,4.05,7.84,4.30,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,True,0.0,REM
95652,15,37656,Fábio,1,266,FLU,7,-0.70,8.98,4.17,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,True,0.0,FLU
95653,15,39148,Hulk,5,266,FLU,6,0.00,11.80,4.55,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0,FLU
95654,15,39656,Alan Franco,4,282,CAM,7,0.00,5.73,2.52,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0,CAM
95655,15,39850,Vagner Mancini,6,280,RBB,7,2.38,8.12,5.11,...,0.0,0.0,0.0,6.0,0.0,0.0,0.0,True,0.0,RBB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96396,15,150180,Ramon Rique,4,267,VAS,6,1.50,1.52,1.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0,VAS
96397,15,150197,Osorio,3,276,SAO,6,0.00,1.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0,SAO
96398,15,150757,Samuel Pierri,4,277,SAN,6,0.00,2.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0,SAN
96399,15,150825,Breno,3,280,RBB,6,0.00,0.92,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0,RBB
96400,15,150826,Nícollas,5,264,COR,6,0.00,1.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,0.0,COR

In [38]:
from cartola_collector import DATA_DIR

mercado = pd.read_parquet(DATA_DIR / f"mercado_atual.parquet")
mercado

,atleta_id,apelido,posicao_id,clube_id,preco,media,status_id,jogos
0,99552,Rossi,1,262,9.60,5.24,7,13
1,103183,Andrew,1,262,3.00,0.00,6,0
2,122318,Dyogo Alves,1,262,3.00,0.00,6,0
3,130189,Léo Nannetti,1,262,2.00,0.00,6,0
4,68806,Neto,1,263,8.52,4.09,7,7
...,...,...,...,...,...,...,...,...
744,92273,Odair Hellmann,6,293,8.40,5.12,7,13
745,126977,Fernando Seabra,6,294,7.91,5.07,7,15
746,107771,Fábio Matias,6,315,6.84,2.91,7,5
747,37457,Léo Condé,6,364,7.84,4.30,7,11
748,104027,Rafael Guanaes,6,2305,7.31,4.02,7,13

In [ ]:
comparacao = mercado.merge(
    rodada_15[['atleta_id', 'media']],
    on='atleta_id',
    how='inner',
    suffixes=('_mercado', '_rodada_15')
)
comparacao[['atleta_id', 'media_mercado', 'media_rodada_15']]

,atleta_id,apelido,posicao_id,clube_id,preco,media_mercado,status_id,jogos,media_rodada_15,diff
0,99552,Rossi,1,262,9.60,5.24,7,13,5.24,0.0
1,103183,Andrew,1,262,3.00,0.00,6,0,0.00,0.0
2,122318,Dyogo Alves,1,262,3.00,0.00,6,0,0.00,0.0
3,130189,Léo Nannetti,1,262,2.00,0.00,6,0,0.00,0.0
4,68806,Neto,1,263,8.52,4.09,7,7,4.09,0.0
...,...,...,...,...,...,...,...,...,...,...
744,92273,Odair Hellmann,6,293,8.40,5.12,7,13,5.12,0.0
745,126977,Fernando Seabra,6,294,7.91,5.07,7,15,5.07,0.0
746,107771,Fábio Matias,6,315,6.84,2.91,7,5,2.91,0.0
747,37457,Léo Condé,6,364,7.84,4.30,7,11,4.30,0.0
748,104027,Rafael Guanaes,6,2305,7.31,4.02,7,13,4.02,0.0

In [7]:
df_ppr_2026[df_ppr_2026.apelido == "Garro"]

,rodada,atleta_id,apelido,posicao_id,clube_id,clube_abreviacao,status_id,pontos,preco,media,...,scout_A,scout_FT,scout_PC,scout_V,scout_PS,scout_PP,scout_CV,jogou,scout_GC,clube_nome
85958,1,117632,Garro,4,264,COR,6,10.0,13.32,0.000000,...,1.0,0.0,0.0,0.0,0.0,NaN,0.0,True,0.0,COR
86649,2,117632,Garro,4,264,COR,6,0.0,13.32,10.000000,...,1.0,0.0,0.0,0.0,0.0,NaN,0.0,True,0.0,COR
87350,3,117632,Garro,4,264,COR,7,7.0,13.52,5.000000,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
88054,4,117632,Garro,4,264,COR,7,5.7,13.49,5.666667,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
88765,5,117632,Garro,4,264,COR,7,1.1,11.93,5.675000,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
89485,6,117632,Garro,4,264,COR,7,1.6,11.12,4.760000,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
90213,7,117632,Garro,4,264,COR,6,7.5,12.08,4.233333,...,3.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
90943,8,117632,Garro,4,264,COR,7,0.0,10.67,4.700000,...,3.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
91674,9,117632,Garro,4,264,COR,2,2.8,10.63,4.112500,...,3.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
92410,10,117632,Garro,4,264,COR,2,4.4,10.88,3.966667,...,3.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
93150,11,117632,Garro,4,264,COR,7,1.0,10.18,4.010000,...,3.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
93893,12,117632,Garro,4,264,COR,7,0.3,9.79,3.736364,...,3.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
94637,13,117632,Garro,4,264,COR,7,8.4,10.91,3.450000,...,4.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
95385,14,117632,Garro,4,264,COR,7,2.5,10.10,3.830769,...,4.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR
96133,15,117632,Garro,4,264,COR,7,15.6,12.24,3.735714,...,6.0,1.0,0.0,0.0,0.0,0.0,0.0,True,0.0,COR