In [ ]:
from cartola_data.datasets import read_datasets

df_players_per_round, df_matches, df_odds = read_datasets()
df_odds.describe()

,rodada,clube_id,prob_win,prob_draw,prob_loss,temporada
count,2366.000000,2366.000000,2366.000000,2366.000000,2366.000000,2366.000000
mean,18.572274,358.331361,0.325013,0.349975,0.325013,2024.268808
std,10.607810,338.028630,0.121667,0.021494,0.121667,1.012613
min,2.000000,262.000000,0.060000,0.250000,0.060000,2023.000000
25%,9.000000,267.000000,0.230000,0.340000,0.230000,2023.000000
50%,18.000000,282.000000,0.330000,0.350000,0.330000,2024.000000
75%,28.000000,290.000000,0.410000,0.360000,0.410000,2025.000000
max,38.000000,2305.000000,0.690000,0.420000,0.690000,2026.000000

In [2]:
df_odds

      rodada  clube_id  prob_win  prob_draw  prob_loss  temporada
0          3       262      0.52       0.34       0.14       2023
1          3       263      0.14       0.34       0.52       2023
2          3       264      0.15       0.34       0.51       2023
3          3       265      0.19       0.35       0.46       2023
4          3       266      0.32       0.37       0.31       2023
...      ...       ...       ...        ...        ...        ...
2361      16       347      0.38       0.35       0.27       2026
2362      16       349      0.40       0.36       0.24       2026
2363      16       364      0.28       0.38       0.34       2026
2364      16       386      0.21       0.36       0.43       2026
2365      16      2305      0.24       0.36       0.40       2026

[2366 rows x 6 columns]